apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-blue
  namespace: blue-green
  labels:
    app: my-app
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
      version: blue
  template:
    metadata:
      labels:
        app: my-app
        version: blue
    spec:
      containers:
      - name: my-app
        image: dockersamples/examplevotingapp_vote

        ports:
        - containerPort: 8080
        env:
        - name: APP_VERSION
          value: "blue-1.0.0"
        - name: ENVIRONMENT
          value: "blue"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-blue-service
  namespace: blue-green
  labels:
    app: my-app
    version: blue
spec:
  selector:
    app: my-app
    version: blue
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-green
  namespace: blue-green
  labels:
    app: my-app
    version: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
      version: green
  template:
    metadata:
      labels:
        app: my-app
        version: green
    spec:
      containers:
      - name: my-app
        image: nginx:1.25
        ports:
        - containerPort: 8080
        env:
        - name: APP_VERSION
          value: "green-1.0.0"
        - name: ENVIRONMENT
          value: "green"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-green-service
  namespace: blue-green
  labels:
    app: my-app
    version: green
spec:
  selector:
    app: my-app
    version: green
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP 

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-main-service
  namespace: blue-green
  labels:
    app: my-app
spec:
  selector:
    app: my-app
    version: blue  
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer    